// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN78kR9sg8DyXQCUgGu7it4zuoV2VttBg',
    appId: '1:593793808284:web:2bb46b425d96dfddb0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    authDomain: 'engram-26a3a.firebaseapp.com',
    storageBucket: 'engram-26a3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCleynG97H14xwoeQPyBkYakkuIC1wGcq4',
    appId: '1:593793808284:android:bc2683e1816b61f2b0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTkhmUcpNCLT6JrJOOIC3RV8t7x-lRiLs',
    appId: '1:593793808284:ios:8c647ab5e614a11db0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
    androidClientId: '593793808284-p1ijmejeqep15lburbkgfirsh1r63dje.apps.googleusercontent.com',
    iosClientId: '593793808284-3lici2b3q9a9aakq5deullkh94a23b87.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.engram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTkhmUcpNCLT6JrJOOIC3RV8t7x-lRiLs',
    appId: '1:593793808284:ios:8c647ab5e614a11db0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
    androidClientId: '593793808284-p1ijmejeqep15lburbkgfirsh1r63dje.apps.googleusercontent.com',
    iosClientId: '593793808284-3lici2b3q9a9aakq5deullkh94a23b87.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.engram',
  );
}
